use_frameworks!
platform :ios, '11.0'
install! 'cocoapods', :share_schemes_for_development_pods => true

target 'NFCDecoder_Example' do
  pod 'NFCDecoder', :path => '../'
  target 'NFCDecoder_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Impekable LLC"
end


