use_frameworks!
platform :ios, '11.0'

target 'NfcDecoder_Example' do
  pod 'NfcDecoder', :path => '../'
  target 'NfcDecoder_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Impekable LLC"
end


